image: registry.gitlab.com/pages/hugo/hugo_extended

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo && gzip -k -6 $(find public -type f)
  artifacts:
    paths:
    - public
  only:
  - master
